name: jellyseerr

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - lab
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    volumes:
      - ../data:/app/config
    ports:
      - '5055:5055'
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.requests.rule=Host(`requests.thegarden`)
      - traefik.http.routers.requests.entrypoints=websecure
      - traefik.http.routers.requests.tls=true
      - traefik.http.services.requests.loadbalancer.server.port=5055

networks:
  lab:
    external: true
