name: radarr

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - lab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ../data:/config
      - /mnt/docker-data/media/movies:/movies
      - /mnt/docker-scratch/downloads:/downloads
    ports:
      - '38083:7878'
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.movie.rule=Host(`movie.thegarden`)
      - traefik.http.routers.movie.entrypoints=web
      - traefik.http.services.movie.loadbalancer.server.port=7878

networks:
  lab:
    external: true
