name: sabnzbd

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - lab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ../data:/config
      - /mnt/docker-scratch/downloads/usenet:/downloads
    ports:
      - '38080:8080'
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.usenet.rule=Host(`usenet.thegarden`)
      - traefik.http.routers.usenet.entrypoints=websecure
      - traefik.http.routers.usenet.tls=true
      - traefik.http.services.usenet.loadbalancer.server.port=8080

networks:
  lab:
    external: true
