name: deluge

services:
  deluge:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    cap_add:
      - NET_ADMIN
    networks:
      - lab
    ports:
      - '8112:8112'
      - '8118:8118'
      - '58846:58846'
      - '58946:58946'
    volumes:
      - /mnt/docker-scratch/downloads/torrents:/data
      - ../data/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - 'NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1'
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - UMASK=000
      - PUID=0
      - PGID=0
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrents.rule=Host(`torrents.thegarden`)
      - traefik.http.routers.torrents.entrypoints=web
      - traefik.http.services.torrents.loadbalancer.server.port=8112

networks:
  lab:
    external: true
