name: overseerr

services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - lab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ../data:/config
    ports:
      - '5055:5055'
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.requests.rule=Host(`requests.thegarden`)
      - traefik.http.routers.requests.entrypoints=web
      - traefik.http.services.requests.loadbalancer.server.port=5055

networks:
  lab:
    external: true
