name: grafana

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - lab
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - TZ=America/New_York
    volumes:
      - ../data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    ports:
      - '3000:3000'
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.thegarden`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000

networks:
  lab:
    external: true
